import studentsRaw from '../data/students.json';
import questions70Raw from '../data/seedQuestions.json';
import { Course, GradeBoundary, NotificationItem, Question, QuestionBank, Quiz, Result, Student, SystemConfig } from '../types';

export const INITIAL_STUDENTS: Student[] = (studentsRaw as Student[]).map((student) => ({
  ...student,
  level: '100 Level',
  class: '100 Level Class',
}));

export const DEFAULT_GRADING_SCALE: GradeBoundary[] = [
  { grade: 'A', minPercent: 70, maxPercent: 100, points: 5, description: 'Excellent' },
  { grade: 'B', minPercent: 65, maxPercent: 69.99, points: 4, description: 'Very Good' },
  { grade: 'C', minPercent: 60, maxPercent: 64.99, points: 3, description: 'Good' },
  { grade: 'D', minPercent: 55, maxPercent: 59.99, points: 2, description: 'Fair' },
  { grade: 'E', minPercent: 50, maxPercent: 54.99, points: 1, description: 'Pass' },
  { grade: 'F', minPercent: 0, maxPercent: 49.99, points: 0, description: 'Fail' },
];

export const INITIAL_CONFIG: SystemConfig = {
  institution: 'University of Nigeria, Nsukka',
  campus: 'Enugu Campus (UNEC)',
  faculty: 'Faculty of Law',
  academicSession: '2025/2026 Academic Session - 100 Level',
  gradingScale: DEFAULT_GRADING_SCALE,
  syncMode: 'localStorage',
};

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-phil-101',
    code: 'PHIL 101',
    title: 'Introduction to Philosophy',
    description: 'Foundations of philosophical reasoning, logic, ethics, and critical thinking.',
    creditUnits: 3,
    semester: 'First Semester',
    lecturer: 'Department of Philosophy',
  },
  {
    id: 'course-law-411',
    code: 'LAW 411',
    title: 'Nigerian Constitutional Law',
    description: 'Supremacy of the constitution, separation of powers, fundamental rights and federalism.',
    creditUnits: 4,
    semester: 'First Semester',
    lecturer: 'Faculty of Law Board',
  },
  {
    id: 'course-law-421',
    code: 'LAW 421',
    title: 'Jurisprudence & Legal Theory',
    description: 'Schools of jurisprudence, theories of law and justice.',
    creditUnits: 3,
    semester: 'First Semester',
    lecturer: 'Faculty of Law Board',
  },
  {
    id: 'course-law-431',
    code: 'LAW 431',
    title: 'Commercial Law & Sale of Goods',
    description: 'Contracts, sale of goods and commercial transactions.',
    creditUnits: 3,
    semester: 'First Semester',
    lecturer: 'Faculty of Law Board',
  },
];

export const SEED_QUESTIONS_CONSTITUTIONAL: Question[] = questions70Raw as Question[];

// Questions for Jurisprudence sample quiz
export const SEED_QUESTIONS_JURISPRUDENCE: Question[] = [
  {
    id: 'jq1',
    questionText: 'Who defined law as the command of an uncommanded sovereign backed by threats of sanction?',
    options: {
      A: 'Hans Kelsen',
      B: 'John Austin',
      C: 'H.L.A. Hart',
      D: 'Thomas Aquinas',
    },
    correctAnswer: 'B',
    explanation: 'John Austin in Province of Jurisprudence Determined established the Imperative/Command Theory of Law.',
  },
  {
    id: 'jq2',
    questionText: 'Which philosopher authored "The Morality of Law" and proposed the eight internal desiderata of law?',
    options: {
      A: 'Ronald Dworkin',
      B: 'Lon L. Fuller',
      C: 'John Finnis',
      D: 'Jeremy Bentham',
    },
    correctAnswer: 'B',
    explanation: 'Lon L. Fuller introduced procedural natural law and the 8 principles of inner morality.',
  },
  {
    id: 'jq3',
    questionText: 'Hans Kelsen posited that every legal system derives its ultimate validity from what foundational norm?',
    options: {
      A: 'The Volksgeist',
      B: 'The Grundnorm',
      C: 'Rule of Recognition',
      D: 'Lex Aeterna',
    },
    correctAnswer: 'B',
    explanation: 'Kelsen’s Pure Theory of Law centers on the hierarchical validity derived from the Grundnorm.',
  },
  {
    id: 'jq4',
    questionText: 'The concept of the "Rule of Recognition" was introduced into analytical jurisprudence by:',
    options: {
      A: 'H.L.A. Hart',
      B: 'Karl Olivecrona',
      C: 'Joseph Raz',
      D: 'Lord Denning',
    },
    correctAnswer: 'A',
    explanation: 'H.L.A. Hart in "The Concept of Law" introduced the secondary rule of recognition.',
  },
  {
    id: 'jq5',
    questionText: 'The Historical School of Jurisprudence, championed by Friedrich Carl von Savigny, posits that law is:',
    options: {
      A: 'Imposed from above by sovereign command',
      B: 'A tool of capitalist exploitation',
      C: 'Found in the common consciousness of the people (Volksgeist)',
      D: 'Derived purely from divine revelation',
    },
    correctAnswer: 'C',
    explanation: 'Savigny argued that law develops like language from the internal spirit and organic culture of the people.',
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'quiz-const-law-01',
    courseId: 'course-law-411',
    courseCode: 'LAW 411',
    courseTitle: 'Nigerian Constitutional Law',
    title: 'Constitutional Law Mid-Semester CBT Examination',
    totalQuestions: 70,
    durationMinutes: 25,
    date: 'Tuesday',
    startTime: '13:00',
    scheduledDateTime: new Date(Date.now() + 3600000).toISOString(), // 1 hour from now
    status: 'active', // Active so students can immediately test the 70 questions!
    questions: SEED_QUESTIONS_CONSTITUTIONAL,
    instructions: '1. This examination consists of 70 objective questions.\n2. Total duration is 25 minutes.\n3. Each question carries 1 mark.\n4. Questions will automatically submit when the timer reaches 00:00.\n5. Do not switch tabs or minimize the browser window during the test.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'quiz-juris-02',
    courseId: 'course-law-421',
    courseCode: 'LAW 421',
    courseTitle: 'Jurisprudence & Legal Theory',
    title: 'Jurisprudence Diagnostic Test 1',
    totalQuestions: 5,
    durationMinutes: 10,
    date: 'Thursday',
    startTime: '10:00',
    scheduledDateTime: new Date(Date.now() + 86400000 * 2).toISOString(), // 2 days later
    status: 'scheduled',
    questions: SEED_QUESTIONS_JURISPRUDENCE,
    instructions: '1. Answer all questions.\n2. Duration: 10 minutes.\n3. Attempt to complete before time runs out.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'quiz-comm-03',
    courseId: 'course-law-431',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    title: 'Commercial Law Continuous Assessment (Past Exam)',
    totalQuestions: 5,
    durationMinutes: 15,
    date: 'Monday',
    startTime: '09:00',
    scheduledDateTime: new Date(Date.now() - 86400000 * 3).toISOString(), // 3 days ago
    status: 'completed',
    questions: SEED_QUESTIONS_JURISPRUDENCE,
    instructions: 'Past completed test for revision and result archiving.',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
];

// Initial per-course question banks (synced to Firebase like every other collection).
// LAW 411 ships with the full 70-question bank so Practice Arena works instantly.
export const INITIAL_QUESTION_BANKS: QuestionBank[] = [
  {
    id: 'bank_course-law-411',
    courseId: 'course-law-411',
    courseCode: 'LAW 411',
    courseTitle: 'Nigerian Constitutional Law',
    questions: questions70Raw as Question[],
    updatedAt: new Date().toISOString(),
    questionsPerAttempt: 70,
  },
  {
    id: 'bank_course-law-421',
    courseId: 'course-law-421',
    courseCode: 'LAW 421',
    courseTitle: 'Jurisprudence & Legal Theory',
    questions: [],
    updatedAt: new Date().toISOString(),
    questionsPerAttempt: 70,
  },
  {
    id: 'bank_course-phil-101',
    courseId: 'course-phil-101',
    courseCode: 'PHIL 101',
    courseTitle: 'Introduction to Philosophy',
    questions: [],
    updatedAt: new Date().toISOString(),
    questionsPerAttempt: 70,
  },
];

// Sample ranked results for the past exam and initial leaderboard
export const INITIAL_RESULTS: Result[] = [
  {
    id: 'res-1',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/298761',
    studentName: 'Abafor Chinaza Happiness',
    totalQuestions: 70,
    correctAnswers: 64,
    wrongAnswers: 6,
    unanswered: 0,
    score: 64,
    percentage: 91.43,
    grade: 'A',
    rank: 1,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1200000).toISOString(),
    submissionType: 'early',
    answers: {},
  },
  {
    id: 'res-2',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2024/283415',
    studentName: 'Abonyi Ezinne Princess',
    totalQuestions: 70,
    correctAnswers: 61,
    wrongAnswers: 9,
    unanswered: 0,
    score: 61,
    percentage: 87.14,
    grade: 'A',
    rank: 2,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1400000).toISOString(),
    submissionType: 'early',
    answers: {},
  },
  {
    id: 'res-3',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/296490',
    studentName: 'Adah Favour Sunday',
    totalQuestions: 70,
    correctAnswers: 58,
    wrongAnswers: 11,
    unanswered: 1,
    score: 58,
    percentage: 82.86,
    grade: 'A',
    rank: 3,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1500000).toISOString(),
    submissionType: 'auto_timer',
    answers: {},
  },
  {
    id: 'res-4',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/290621',
    studentName: 'Adama Joy',
    totalQuestions: 70,
    correctAnswers: 53,
    wrongAnswers: 17,
    unanswered: 0,
    score: 53,
    percentage: 75.71,
    grade: 'A',
    rank: 4,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1450000).toISOString(),
    submissionType: 'early',
    answers: {},
  },
  {
    id: 'res-5',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/297555',
    studentName: 'Adetoye Freedom Beulah',
    totalQuestions: 70,
    correctAnswers: 47,
    wrongAnswers: 23,
    unanswered: 0,
    score: 47,
    percentage: 67.14,
    grade: 'B',
    rank: 5,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1500000).toISOString(),
    submissionType: 'auto_timer',
    answers: {},
  },
  {
    id: 'res-6',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/295956',
    studentName: 'Adinde Kenneth',
    totalQuestions: 70,
    correctAnswers: 43,
    wrongAnswers: 27,
    unanswered: 0,
    score: 43,
    percentage: 61.43,
    grade: 'C',
    rank: 6,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1500000).toISOString(),
    submissionType: 'auto_timer',
    answers: {},
  },
  {
    id: 'res-7',
    quizId: 'quiz-comm-03',
    quizTitle: 'Commercial Law Continuous Assessment (Past Exam)',
    courseCode: 'LAW 431',
    courseTitle: 'Commercial Law & Sale of Goods',
    studentRegNo: '2025/293428',
    studentName: 'Adoyi Happiness',
    totalQuestions: 70,
    correctAnswers: 39,
    wrongAnswers: 31,
    unanswered: 0,
    score: 39,
    percentage: 55.71,
    grade: 'D',
    rank: 7,
    submittedAt: new Date(Date.now() - 86400000 * 3 + 1380000).toISOString(),
    submissionType: 'early',
    answers: {},
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Constitutional Law CBT Examination Active',
    message: 'LAW 411: Nigerian Constitutional Law Examination (70 Questions, 25 Minutes) is now active and accessible to all 400-level UNEC Law students.',
    date: 'Just now',
    type: 'exam_alert',
    targetCourse: 'LAW 411',
  },
  {
    id: 'notif-2',
    title: 'Jurisprudence CBT Quiz Scheduled',
    message: 'LAW 421: Jurisprudence & Legal Theory Diagnostic Test has been scheduled for Thursday at 10:00 AM. Please ensure you have stable internet connection.',
    date: 'Today, 08:30 AM',
    type: 'quiz_schedule',
    targetCourse: 'LAW 421',
  },
  {
    id: 'notif-3',
    title: 'Commercial Law Quiz Results Released',
    message: 'Results for LAW 431: Commercial Law & Sale of Goods Continuous Assessment have been computed and published on the Past Results portal.',
    date: 'Yesterday, 04:15 PM',
    type: 'result',
    targetCourse: 'LAW 431',
  },
  {
    id: 'notif-4',
    title: 'Official 030 Class Roster Verified',
    message: 'All 356 registered candidates of the 030 Law Class, UNEC have been verified in the CBT examination database. Use your exact registration number to log in.',
    date: '2 days ago',
    type: 'general',
  },
];
